version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - FORCE_COLOR=1
    volumes:
      - .:/app
      - /app/node_modules
    command: pnpm dev
    restart: unless-stopped
    tty: true
    stdin_open: true
